apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollen8-backend
  labels:
    app: pollen8
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pollen8
      tier: backend
  template:
    metadata:
      labels:
        app: pollen8
        tier: backend
    spec:
      containers:
      - name: pollen8-backend
        image: ${ECR_REGISTRY}/pollen8-backend:${IMAGE_TAG}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: pollen8-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pollen8-secrets
              key: DATABASE_URL
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10