apiVersion: v1
kind: Secret
metadata:
  name: pollen8-secrets
  namespace: pollen8
type: Opaque
data:
  # Database Credentials
  DB_USERNAME: <base64_encoded_username>
  DB_PASSWORD: <base64_encoded_password>
  
  # JWT Secret
  JWT_SECRET: <base64_encoded_jwt_secret>
  
  # Twilio API Credentials
  TWILIO_ACCOUNT_SID: <base64_encoded_account_sid>
  TWILIO_AUTH_TOKEN: <base64_encoded_auth_token>
  
  # AWS Credentials
  AWS_ACCESS_KEY_ID: <base64_encoded_access_key_id>
  AWS_SECRET_ACCESS_KEY: <base64_encoded_secret_access_key>
  
  # Other API Keys
  # Add any additional API keys or sensitive information here
  
---
# Example of how to use these secrets in a deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pollen8-backend
  namespace: pollen8
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pollen8-secrets
              key: DB_PASSWORD
        # Add other environment variables as needed

---
# RBAC configuration to limit access to secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pollen8
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["pollen8-secrets"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: pollen8
subjects:
- kind: ServiceAccount
  name: default
  namespace: pollen8
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io